### ISSUE TITLE
org/sleuthkit/datamodel/SleuthkitJNI has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by rubiodamian** [bannsec/autopsy_docker#7]
Hi everyone, it seems that there is a issue with the version of java in the last image build.

this is the error that i get running with docker:
org.netbeans.InvalidException: StandardModule:org.sleuthkit.autopsy.core jarFile: /opt/autopsy/autopsy/modules/org-sleuthkit-autopsy-core.jar: java.lang.UnsupportedClassVersionError: org/sleuthkit/datamodel/SleuthkitJNI has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by bannsec** [comment]
Thanks for the heads up. Looking at it, I'm not sure exactly the solution right now. It's basically both requiring Java 8 and requiring Java 11.

I've opened a ticket with autopsy for now:

https://github.com/sleuthkit/autopsy/issues/6472

**Comment by bannsec** [comment]
This appears to have been fixed. Docker image has been rebuilt. Looks to be working again.

**Comment by firec0de** [comment]
not fixed
